### ISSUE TITLE
CPU and RAM load

### ISSUE THREAD

**Issue by tomek-szczesny** [hominoids/logenv#1]
Hi,

I've been thinking about extracting a system stat portion from pistackmon code to become a standalone application, but you're way ahead of me.
In fact I would gladly adapt this program for my own system monitoring needs in the future.

I'm not sure how useful you'd find such features, but here are my methods for extracting CPU and memory loads:
https://github.com/tomek-szczesny/pistackmon/blob/00af1e19d835a3c15ae241b9c76be15c1ba2edc1/sw/src/pistackmond.cpp#L312

**Comment by hominoids** [comment]
That data collection can be easily added.  This tool is meant to be a cmdline data collector and aggregator so it fits in well.  I've added it to the project near-term todo list. 
```
Power only chart
option --xmtics sets x-axis major second tics
option --title sets chart title
add /proc/stat and /proc/meminfo data
mcp9808 sensor support
smartpower2 tty initialization
```

**Comment by tomek-szczesny** [comment]
I was hoping I could use it as a dependency for my future projects. I remember I implemented some of these measurements more than once, hence I was thinking about an external command line tool to obtain these values instead.

Since your tool seems to serve some data cooked (such as temperatures converted to Celsius), I offered methods of converting raw `/proc` data into CPU and Memory loads.

The CPU load calculation is particularly tricky because one has to grab two data points with a known time span between them.
If `logenv` had to output CPU load on each run (rather than in the built-in loop), I suppose that the previous `/proc/stat` would have to be stored in `/tmp` along with a precise timestamp. 
This is more effort than I would like to ask you for, so I'd put that in a long term todo, and perhaps implement this myself once I actually need CPU load measurements for some new project.

**Comment by hominoids** [comment]
I finished up everything on my list including being able to chart any combination of data sources.  I also started to add /proc/stat data.  Right now it only uses the -s seconds count for measurement duration, so no single-shot yet.  For that, I’m thinking of using a fixed time(50ms) and or requiring the user to provide one with the -u command line option, solely for single-shot mode.  The memory usage portion looks pretty straight forward so that shouldn’t be a problem.  Here is an example chart from one of the test data sets used during testing.  The Ambient Temperature is from a MCP9808.
![ocl-m2_g610-a76_1](https://github.com/user-attachments/assets/7a0b2a65-fa7a-45d3-b070-89ec876a642e)
The GPU test is running the first 4 minutes and then the CPU test runs.  The drop in core usage in the middle is the OpenCL kernel change from floating point to integer tests and the busy part with the power increase at the end is when the Memory and PCIe speed test are being performed.  The saw tooth pattern in the temperature plot is from the fan turning on and off which corresponds nicely to the power spikes in the Watts plot line.  I’m not sure that I implemented the aggregate CPU usage correctly.  It definitely behaves differently then the individual core readings.  Any feedback you have would be appreciated.  I also need to test the new TTY initialization on the SmartPower2.

For the future, I’m thinking about implementing access to all the other sensors I use, including the ones from my air quality project.  It could be an easy way to deploy them bare metal or have access to them, on anything that runs Linux.  A udp and or mqqt front-end could be developed for remote access from other applications or to feed databases.  Bottom line, it would be a simple and lightweight means, with the use of a cron entry, to log and or send data from multiple sources in one command on any SBC or server. Hmmmm, I’m liking this idea.

**Comment by tomek-szczesny** [comment]
Very interesting set of graphs, thanks for sharing. This also clearly shows why I'll skip NVMe in my laptop build.

As for the CPU load measurement, I ran your program on my M1 server and H3 desktop. On both platforms it seems to behave similarly.
I investigated your code and I can see what went wrong with aggregate CPU time. I'll prepare a pull request later today that computes CPU load based on stat data only, independent from `INTERACTIVE_ENABLE`, `tck`, or a number of logical CPU cores.
Aggregate CPU time totals to n*100%, where "n" is a number of logical CPU cores. That's where things went south in your implementation.

For a single shot mode I suggest a fixed time of 1/n seconds, where "n" is a number of CPU cores. This will guarantee results with 1% resolution for aggregate measurement, at a minimum time. 50ms is definitely not enough, as each core will have 20% resolution.

I would also consider introducing new options:
-U - prints the CPU load per each CPU core (no aggregate)
-u - print the aggregate CPU load only
-some new option to skip the time column (or an option to include it, complementary to `-d`).
Also a support of fractional polling interval would be nice, if it doesn't complicate things too much.
All this boils down to my desire to obtain aggregated CPU load and nothing more, that I could pipe into another program that does something with these values, such as driving LEDs.

There is one last thing that I'm not quite sure about.
https://github.com/hominoids/logenv/blob/6a592279012a59f02f1b812660c969bd4c13ace8/logenv.c#L592
I checked again and on both of my systems the stat unit of time is 10ms. 32-bit variables may become insufficient after 124 days on a quad core machine. M1 has an uptime of almost 170 days and one of the numbers in /proc/stat is 4179487673.
I'm not sure what will happen after hitting 2^32, but I can imagine that those values are 64-bit.

**Comment by hominoids** [comment]
Thanks for the feedback.  I merged your changes but I have several things going on today so I'll take a closer look later.

**Comment by hominoids** [comment]
I increased the type size of the usage arrays to a double, which I tested to be 16 bytes on the M2.  I also changed to millisecond resolution for the interval count to support fractional polling and removed the count output for all one shot operations.  The -u usage now starts at zero but I still have to separate the aggregate and core data and implement -U and -u.

The usage works much better but I think the calculations might still be incorrect.  I noticed the numbers weren't as responsive as I thought they should be and didn't seem to match htop.  In looking at the code closer I saw that the CPU aggregate was being added to the summation of s and sum at line 696.  Removing  u[0][c] and use[0][c] seemed to give better resolution and responsiveness.  What do you think? 
```
                    s = u[1][c] + u[2][c] + u[3][c] + u[4][c] \
                        + u[5][c] + u[6][c] + u[7][c] + u[8][c] + u[9][c];
                    sum = use[1][c] + use[2][c] + use[3][c] + use[4][c] \
                        + use[5][c] + use[6][c] + use[7][c] + use[8][c] + use[9][c];
```
EDIT: OK, I see that removing u[0][c] and use[0][c] is completely wrong so the comment can be ignored. I'll be reverting these changes.

**Comment by tomek-szczesny** [comment]
Yes, I believe the results are fine if the interval is reasonably high, such as 1s or more.
I just tested logenv on a 12-core machine with WLS, and `-u` seems to work fine as well.
htop has a default refresh rate of 1500ms, hence it could display slightly different values.

Thanks for all the changes, much appreciated!

It's incredible how fast it builds and runs. I should probably switch from C++ to C as well.

**Comment by tomek-szczesny** [comment]
I just noticed this and will spare us creating another issue:
https://github.com/hominoids/logenv/blob/46f420d890ac13ef39dda3571e8ce61a3f5098d3/logenv.c#L59-L60

I believe that on the first iteration this code reads beyond the range of arguments. 
In other words, the last argument has index `argc-1`.

**Comment by hominoids** [comment]
Fixed, that was a good catch.  Especially since it wasn't causing any problem, with argv[0] being the command, but it definitely wasn't correct.  Thanks!

**Comment by tomek-szczesny** [comment]
Hm, I think I didn't make myself clear :)
Reading `argv[0]` isn't a big deal, but `argv[argc]` will always point at a memory location outside the list of arguments.
`argv[argc-1]` is the actual last argument, so the while loop should begin execution with `i = argc - 1`, or the while loop condition should be `--i`. The latter is even better because argv[0] won't be parsed either.

I've drawn inspiration from your code today and I'm halfway done with a simple tool for myself. The last argument in my test runs was numerical, and I couldn't understand why I got random numbers while trying to parse it in my code. :)

**Comment by hominoids** [comment]
Hmm,  this is what I had:

```
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {

    int i = argc;
    while (i--) {
    printf("i = %d, argc = %d, argv = %s\n", i, argc, argv[i]);
    }
}

```

```
$ gcc test.c -o test
$ ./test a b c d e
i = 5, argc = 6, argv = e
i = 4, argc = 6, argv = d
i = 3, argc = 6, argv = c
i = 2, argc = 6, argv = b
i = 1, argc = 6, argv = a
i = 0, argc = 6, argv = ./test
```

This is what I changed it to:
```
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {

    int i = argc;
    while (i-- > 1) {
    printf("i = %d, argc = %d, argv = %s\n", i, argc, argv[i]);
    }
}
```

```
$ gcc test.c -o test
$ ./test a b c d e
i = 5, argc = 6, argv = e
i = 4, argc = 6, argv = d
i = 3, argc = 6, argv = c
i = 2, argc = 6, argv = b
i = 1, argc = 6, argv = a

```

I appreciate your feedback but I don't understand what I'm missing?

**Comment by tomek-szczesny** [comment]
You're right, there's no problem with your code anymore. Sorry for misleading us. :)
Even though C language was a part of high school and university curriculum, I still consider myself novice. :)
